# Generated by Django 5.2.3 on 2026-05-26 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0003_job_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrow',
            name='job',
        ),
        migrations.AddField(
            model_name='escrow',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='escrows', to='ManageJobsTasks.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=20),
        ),
    ]
