# Generated by Django 5.2.3 on 2026-07-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0010_jobapplication_bid_amount_jobapplication_proposal'),
        ('contracts', '0002_contract_contractdocument'),
        ('payments', '0003_payment_collection_id_payment_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ManageJobsTasks.task'),
        ),
    ]
