# Generated by Django 5.2.3 on 2026-07-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_contract_alter_payment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('FEE', 'Platform Fee'), ('VAT', 'VAT')], max_length=20),
        ),
    ]
