# Generated by Django 5.2.3 on 2026-07-29 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_billingperiod'),
        ('payments', '0006_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.billingperiod'),
        ),
    ]
