# Generated by Django 5.2.3 on 2026-03-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_kyc_verified_useractivitylog_userkyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
