# Generated by Django 5.2.3 on 2026-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_verified_email_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verified_email',
            field=models.BooleanField(default=True),
        ),
    ]
