# Generated by Django 5.2.3 on 2026-07-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkyc',
            name='bvn',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='nin',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='payout_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfie/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='id_type',
            field=models.CharField(blank=True, choices=[('nin', 'NIN Slip / National ID'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card")], max_length=50),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
