# Generated by Django 5.2.3 on 2026-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userkyc_bvn_userkyc_nin_userkyc_payout_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
