# Generated by Django 5.2.3 on 2026-02-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user_type',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('employer', 'Employer')], db_index=True, max_length=20),
        ),
    ]
