# Generated by Django 5.2.3 on 2026-02-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_plan_is_active_alter_plan_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
