# Generated by Django 5.2.3 on 2026-07-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_dispute_projectsubmission_submissionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='review_note',
            field=models.TextField(blank=True),
        ),
    ]
