# Generated by Django 5.2.3 on 2026-07-28 16:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0010_jobapplication_bid_amount_jobapplication_proposal'),
        ('contracts', '0004_contract_review_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='ManageJobsTasks.task'),
        ),
        migrations.AddField(
            model_name='contract',
            name='task_bidding',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='ManageJobsTasks.taskbidding'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='ManageJobsTasks.jobapplication'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='ManageJobsTasks.job'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contracts.joboffer'),
        ),
        migrations.CreateModel(
            name='TaskOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_days', models.PositiveIntegerField(help_text='Agreed delivery time in days')),
                ('note', models.TextField(blank=True, help_text='Optional scope note / message to the freelancer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bidding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='ManageJobsTasks.taskbidding')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_offers_sent', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_offers_received', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_offers', to='ManageJobsTasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='task_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contracts.taskoffer'),
        ),
    ]
