# Generated by Django 5.2.3 on 2026-07-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_task_contract_task_bidding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='agreement_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cadence',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='grace_period_days',
            field=models.PositiveSmallIntegerField(default=10, help_text='Days after a missed funding before termination opens'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='meeting_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month payment is due', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='review_window_days',
            field=models.PositiveSmallIntegerField(default=4, help_text='Days at period end to review before auto-release'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='agreement_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='cadence',
            field=models.CharField(default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='meeting_terms',
            field=models.TextField(blank=True, help_text='Availability / meeting terms in the agreement'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='payment_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of the month the payment is due (1-28)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('awaiting_funding', 'Awaiting Funding'), ('funded', 'Funded'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('revision_requested', 'Revision Requested'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('active', 'Active'), ('grace', 'Grace Period'), ('pending_termination', 'Pending Termination'), ('terminated', 'Terminated'), ('ended', 'Ended')], default='awaiting_funding', max_length=30),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
