# Generated by Django 5.2.3 on 2026-07-29 00:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_agreement_signed_at_contract_cadence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('funding_due_date', models.DateTimeField(help_text='Employer must fund escrow by this time')),
                ('review_window_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('awaiting_funding', 'Awaiting Funding'), ('funded', 'Funded'), ('in_review', 'In Review'), ('released', 'Released'), ('disputed', 'Disputed'), ('missed', 'Missed')], default='awaiting_funding', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='contracts.contract')),
            ],
            options={
                'ordering': ['contract', 'period_number'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'period_number'), name='unique_period_per_contract')],
            },
        ),
    ]
