# Generated by Django 5.2.3 on 2026-02-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
    ]
