# Generated by Django 5.2.3 on 2026-06-18 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_delete_useractivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactionlog',
            name='target_repr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='target_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_target_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
