# Generated by Django 5.2.3 on 2025-12-03 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full Time"),
                            ("part-time", "Part Time"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                            ("temporary", "Temporary"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("accounting_and_finance", "Accounting and Finance"),
                            ("clerical_and_data_entry", "Clerical and Data Entry"),
                            ("customer_service", "Customer Service"),
                            ("engineering_and_technical", "Engineering and Technical"),
                            ("healthcare", "Healthcare"),
                            ("hospitality_and_tourism", "Hospitality and Tourism"),
                            ("information_technology", "Information Technology"),
                            ("legal", "Legal"),
                            ("marketing_and_advertising", "Marketing and Advertising"),
                            (
                                "sales_and_business_development",
                                "Sales and Business Development",
                            ),
                            (
                                "skilled_trades_and_services",
                                "Skilled Trades and Services",
                            ),
                            ("education_and_training", "Education and Training"),
                            ("creative_and_design", "Creative and Design"),
                            (
                                "real_estate_and_property_management",
                                "Real Estate and Property Management",
                            ),
                            (
                                "transportation_and_logistics",
                                "Transportation and Logistics",
                            ),
                            (
                                "construction_and_maintenance",
                                "Construction and Maintenance",
                            ),
                            ("research_and_development", "Research and Development"),
                            (
                                "non_profit_and_volunteering",
                                "Non-Profit and Volunteering",
                            ),
                            (
                                "government_and_public_service",
                                "Government and Public Service",
                            ),
                            ("media_and_entertainment", "Media and Entertainment"),
                            ("telecommunications", "Telecommunications"),
                            ("energy_and_utilities", "Energy and Utilities"),
                            (
                                "agriculture_and_environment",
                                "Agriculture and Environment",
                            ),
                            ("science_and_technology", "Science and Technology"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tags",
                    models.TextField(
                        help_text="Required skills (comma-separated, max 5 skills)"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="job_images/"),
                ),
                (
                    "files",
                    models.FileField(blank=True, null=True, upload_to="job_uploads/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_expired", models.BooleanField(default=False)),
                (
                    "expiration_date",
                    models.DateTimeField(blank=True, help_text="Project deadline"),
                ),
                ("approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "files",
                    models.FileField(blank=True, null=True, upload_to="applications/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=225)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("admin_support", "Admin Support"),
                            ("customer_service", "Customer_Service"),
                            ("data_analytics", "Data Analytics"),
                            ("design_&_creative", "Design & Creative"),
                            ("legal", "Legal"),
                            ("software_developing", "Software Development"),
                            ("IT_&_networking", "IT & Networking"),
                            ("writing", "Writing"),
                            ("tranlation", "Translation"),
                            ("sales_&_marketing", "Sales & Marketing"),
                        ],
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "budget_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("hourly", "Hourly")],
                        max_length=20,
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        help_text="Required skills (comma-separated, max 5 skills)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expiration_date",
                    models.DateTimeField(blank=True, help_text="Project deadline"),
                ),
                ("is_expired", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("applications_count", models.PositiveIntegerField(default=0)),
                (
                    "description",
                    models.TextField(
                        default="A task", help_text="Detailed project description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="task_images/"),
                ),
                (
                    "files",
                    models.FileField(
                        blank=True,
                        help_text="Optional project files",
                        null=True,
                        upload_to="task_uploads/",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskBidding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_time", models.CharField(max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=250,
                    ),
                ),
                ("read_TC", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
