# Generated by Django 5.2.3 on 2025-12-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ManageJobsTasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
