# Generated by Django 5.2.3 on 2026-05-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0003_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
