# Generated by Django 5.2.3 on 2026-06-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0005_alter_job_salary_max_alter_job_salary_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.TextField(blank=True, help_text='Optional tags (comma-separated, max 10 tags)'),
        ),
    ]
