# Generated by Django 5.2.3 on 2026-07-08 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0007_jobfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskbidding',
            constraint=models.UniqueConstraint(fields=('task', 'freelancer'), name='unique_bid_per_freelancer_per_task'),
        ),
    ]
