# Generated by Django 5.2.3 on 2026-07-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0008_taskbidding_unique_bid_per_freelancer_per_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
