# Generated by Django 5.2.3 on 2026-07-27 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0009_task_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='proposal',
            field=models.TextField(default=''),
        ),
    ]
