# Generated by Django 5.2.3 on 2026-08-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0010_jobapplication_bid_amount_jobapplication_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Job categories',
                'ordering': ['name'],
            },
        ),
    ]
