# Generated by Django 5.2.3 on 2026-08-03 18:07

from django.db import migrations


def seed_categories(apps, schema_editor):
    """Populate JobCategory from the original hardcoded JOB_CATEGORIES so every
    existing Job (whose `category` holds one of these slugs) stays valid and the
    job-post dropdown keeps all its options."""
    JobCategory = apps.get_model("ManageJobsTasks", "JobCategory")
    JOB_CATEGORIES = [
        ('accounting_and_finance', 'Accounting and Finance'),
        ('clerical_and_data_entry', 'Clerical and Data Entry'),
        ('customer_service', 'Customer Service'),
        ('engineering_and_technical', 'Engineering and Technical'),
        ('healthcare', 'Healthcare'),
        ('hospitality_and_tourism', 'Hospitality and Tourism'),
        ('information_technology', 'Information Technology'),
        ('legal', 'Legal'),
        ('marketing_and_advertising', 'Marketing and Advertising'),
        ('sales_and_business_development', 'Sales and Business Development'),
        ('skilled_trades_and_services', 'Skilled Trades and Services'),
        ('education_and_training', 'Education and Training'),
        ('creative_and_design', 'Creative and Design'),
        ('real_estate_and_property_management', 'Real Estate and Property Management'),
        ('transportation_and_logistics', 'Transportation and Logistics'),
        ('construction_and_maintenance', 'Construction and Maintenance'),
        ('research_and_development', 'Research and Development'),
        ('non_profit_and_volunteering', 'Non-Profit and Volunteering'),
        ('government_and_public_service', 'Government and Public Service'),
        ('media_and_entertainment', 'Media and Entertainment'),
        ('telecommunications', 'Telecommunications'),
        ('energy_and_utilities', 'Energy and Utilities'),
        ('agriculture_and_environment', 'Agriculture and Environment'),
        ('science_and_technology', 'Science and Technology'),
        ('other', 'Other'),
    ]
    for slug, name in JOB_CATEGORIES:
        JobCategory.objects.get_or_create(
            slug=slug, defaults={"name": name, "is_active": True}
        )


def unseed_categories(apps, schema_editor):
    JobCategory = apps.get_model("ManageJobsTasks", "JobCategory")
    JobCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0011_jobcategory'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
