# Generated by Django 5.2.3 on 2025-12-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("address", models.CharField(blank=True, max_length=1000, null=True)),
                ("phone", models.CharField(blank=True, max_length=250, null=True)),
                ("facebook", models.URLField(blank=True, max_length=250, null=True)),
                ("gmail", models.EmailField(max_length=254, unique=True)),
                ("linkedin", models.URLField(blank=True, max_length=250, null=True)),
                ("x", models.URLField(blank=True, max_length=250, null=True)),
                ("github", models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MessageContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
    ]
