# Generated by Django 5.2.3 on 2026-07-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobsTasks', '0008_taskbidding_unique_bid_per_freelancer_per_task'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='ManageJobsTasks.job'),
        ),
        migrations.AddField(
            model_name='offer',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='ManageJobsTasks.task'),
        ),
    ]
