"""
Django settings for jobwebsite project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

AUTH_USER_MODEL = 'users.CustomUser'

# DOMAIN = 'freelancetesting.onemillionjobs.com.ng'
DOMAIN = 'lichtcode.pythonanywhere.com'
FRONTEND_URL = f'https://{DOMAIN}/'  # Replace with frontend URL
# LOGIN_URL = 'pages_login'  # URL to redirect to for login

PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY', default='')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['freelancetesting.onemillionjobs.com.ng', 'www.freelancetesting.onemillionjobs.com.ng', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'daphne',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_extensions',
    'channels',
    'Messaging',
    'ManageJobsTasks',
    'company',  # Custom app for company management
    'frontend',  # Custom app for frontend views
    'users',  # Custom app for user accounts
    'authentication',  # Custom app for authentication
    'pricing',  # Custom app for pricing plans
    'reviews',  # Custom app for reviews
    'offers',  # Custom app for offers
    'adminpanel',  # Custom app for admin panel
    'payments',  # Custom app for payment processing

    'notifications',


    'admins',

    'bookmarks',    # Custom app for bookmarks
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'jobwebsite.middleware.request_debugger.RequestDebugMiddleware',  # NEW MIDDLEWARE
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]



ROOT_URLCONF = 'jobwebsite.urls'

SITE_ID = 1

BASE_URL = os.environ.get("BASE_URL", "http://127.0.0.1:8000")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobwebsite.wsgi.application'
ASGI_APPLICATION = 'jobwebsite.asgi.application'

CSRF_TRUSTED_ORIGINS = [
    "https://freelancetesting.onemillionjobs.com.ng",
    "https://www.freelancetesting.onemillionjobs.com.ng",
    "http://freelancetesting.onemillionjobs.com.ng",
    "http://www.freelancetesting.onemillionjobs.com.ng",
]

CORS_ALLOWED_ORIGINS = [
    "https://freelancetesting.onemillionjobs.com.ng",
]
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_HEADERS = ['*']
# CORS_ALLOW_METHODS = ['*']


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# For development, you can use in-memory channel layer (not recommended for production)
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer'
#     }
# }

# settings.py
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "admin-dashboard-cache",
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/subscription.log',
        },

        # NEW HANDLER → Writes request failures
        'request_debug_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/request_debug.log',
        },
    },

    'loggers': {
        'subscriptions': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },

        # NEW LOGGER → For our debugging middleware
        'request_debugger': {
            'handlers': ['request_debug_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "static",  # adjust this based on where your CSS files are
]

# Media files settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'EXCEPTION_HANDLER': 'frontend.exceptions.custom_exception_handler',
}

# mail settings
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'live.smtp.mailtrap.io'
EMAIL_HOST_USER = 'api'
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# -----USE LOCALLY-------

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'iyiolaolubusola@gmail.com'
# EMAIL_HOST_PASSWORD = config('GMAIL_APP_PASSWORD', default='')
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# -----USE ON THE SERVER------

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'freelancetesting.onemillionjobs.com.ng'  # cPanel mail server
# EMAIL_PORT = 465                                       # SMTP SSL port
# EMAIL_USE_SSL = True                                   # use SSL
# EMAIL_USE_TLS = False                                  # disable TLS
# EMAIL_HOST_USER = 'noreply@freelancetesting.onemillionjobs.com.ng'
# EMAIL_HOST_PASSWORD = config('CPANEL_EMAIL_PASSWORD', default='')
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# social login settings
GOOGLE_OAUTH2_CLIENT_ID = config('GOOGLE_OAUTH2_CLIENT_ID', default='')
GOOGLE_OAUTH2_CLIENT_SECRET = config('GOOGLE_OAUTH2_CLIENT_SECRET', default='')
GOOGLE_OAUTH2_REDIRECT_URI = "http://127.0.0.1:8000/api/auth/google/callback/" # for local testing
# GOOGLE_OAUTH2_REDIRECT_URI = "http://freelancetesting.onemillionjobs.com.ng/api/auth/google/callback/" # for production
# GOOGLE_OAUTH2_REDIRECT_URI = "https://lichtcode.pythonanywhere.com/api/auth/google/callback/" # for pythonanywhere


FACEBOOK_CLIENT_ID = config('FACEBOOK_CLIENT_ID', default='')
FACEBOOK_APP_SECRET = config('FACEBOOK_APP_SECRET', default='')
# FACEBOOK_REDIRECT_URI = "https://freelancetesting.onemillionjobs.com.ng/api/auth/facebook/callback/"
FACEBOOK_REDIRECT_URI = "https://lichtcode.pythonanywhere.com/api/auth/google/callback/"

# JWT settings
# These settings are for the Simple JWT package, which provides JSON Web Token authentication.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_COOKIE': 'access',  # Optional, if you want to store access token in a cookie too
}

COOKIE_KWARGS = dict(
    httponly=True,
    secure=not DEBUG,    
)

VAT_ENABLED = True  # Set to True if you want to apply VAT
VAT_RATE = 20  # VAT rate in percentage, e.g., 20 for 20%

PLATFORM_FEE_PERCENTAGE = 10  # Platform fee as a percentage of the transaction amount

# User: onemilm5_freelance_online

# Database: onemilm5_freelance
