"""
Django settings for jobwebsite project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

AUTH_USER_MODEL = 'users.CustomUser'

# Public host used to build absolute links in emails (e.g. password reset).
# Env-driven so prod (Fly) and local can differ without code changes.
DOMAIN = config('DOMAIN', default='one-million-jobs.fly.dev')
_SCHEME = 'http' if DOMAIN.startswith(('localhost', '127.')) else 'https'
FRONTEND_URL = f'{_SCHEME}://{DOMAIN}/'
# Where @login_required sends unauthenticated users (the frontend login page).
# Without this, Django falls back to /accounts/login/ which does not exist here.
LOGIN_URL = '/login/'

# African Money is the only payment gateway (Paystack was removed).
PAYMENT_GATEWAY = 'africanmoney'
AFRICANMONEY_BASE_URL = config('AFRICANMONEY_BASE_URL', default='https://africanmoney.net')
# api_key authenticates collection/create; secret_key authenticates verify (Bearer).
AFRICANMONEY_API_KEY = config('AFRICANMONEY_API_KEY', default='')
AFRICANMONEY_SECRET_KEY = config('AFRICANMONEY_SECRET_KEY', default='')
AFRICANMONEY_COLLECTION_URL = config(
    'AFRICANMONEY_COLLECTION_URL',
    default=f'{AFRICANMONEY_BASE_URL}/collection/create',
)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['freelancetesting.onemillionjobs.com.ng', 'www.freelancetesting.onemillionjobs.com.ng', '*']

# Extra hosts/origins supplied at runtime (e.g. the Fly.io app domain). Comma-separated.
# Example: FLY_APP_HOST=one-million-jobs.fly.dev
_EXTRA_HOSTS = [h.strip() for h in config('EXTRA_ALLOWED_HOSTS', default='').split(',') if h.strip()]
ALLOWED_HOSTS += _EXTRA_HOSTS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.humanize',
    'daphne',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_extensions',
    'channels',
    'Messaging',
    'ManageJobsTasks',
    'company',  # Custom app for company management
    'frontend',  # Custom app for frontend views
    'users',  # Custom app for user accounts
    'authentication',  # Custom app for authentication
    'pricing',  # Custom app for pricing plans
    'reviews',  # Custom app for reviews
    'offers',  # Custom app for offers
    'adminpanel',  # Custom app for admin panel
    'payments',  # Custom app for payment processing
    'contracts',  # Custom app for the hiring flow: offers, contracts, escrow, disputes

    'notifications',


    'admins',

    'bookmarks',    # Custom app for bookmarks
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'jobwebsite.middleware.request_debugger.RequestDebugMiddleware',  # NEW MIDDLEWARE
    'jobwebsite.middleware.onboarding.OnboardingRedirectMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]



ROOT_URLCONF = 'jobwebsite.urls'

SITE_ID = 1

BASE_URL = os.environ.get("BASE_URL", "http://127.0.0.1:8000")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobwebsite.wsgi.application'
ASGI_APPLICATION = 'jobwebsite.asgi.application'

CSRF_TRUSTED_ORIGINS = [
    "https://freelancetesting.onemillionjobs.com.ng",
    "https://www.freelancetesting.onemillionjobs.com.ng",
    "http://freelancetesting.onemillionjobs.com.ng",
    "http://www.freelancetesting.onemillionjobs.com.ng",
]

# Trust the deployment host(s) for CSRF over HTTPS (e.g. the Fly.io domain).
# Comma-separated list of full origins, e.g. CSRF_EXTRA_ORIGINS=https://one-million-jobs.fly.dev
CSRF_TRUSTED_ORIGINS += [o.strip() for o in config('CSRF_EXTRA_ORIGINS', default='').split(',') if o.strip()]

# Django sits behind the Fly.io proxy which terminates TLS; trust its forwarded header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CORS_ALLOWED_ORIGINS = [
    "https://freelancetesting.onemillionjobs.com.ng",
]
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_HEADERS = ['*']
# CORS_ALLOW_METHODS = ['*']


# Channel layer selection:
#   - REDIS_URL set            -> Redis (e.g. Upstash on Fly.io); scales across machines.
#   - USE_INMEMORY_CHANNELS=1  -> in-process layer (single machine; no Redis needed).
#   - otherwise                -> local Redis on 127.0.0.1:6379 (dev default).
REDIS_URL = config('REDIS_URL', default='')
USE_INMEMORY_CHANNELS = config('USE_INMEMORY_CHANNELS', default=False, cast=bool)

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {"hosts": [REDIS_URL]},
        },
    }
elif USE_INMEMORY_CHANNELS:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {"hosts": [('127.0.0.1', 6379)]},
        },
    }

# For development, you can use in-memory channel layer (not recommended for production)
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer'
#     }
# }

# settings.py
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "admin-dashboard-cache",
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'subscription.log',
        },

        # NEW HANDLER → Writes request failures
        'request_debug_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'request_debug.log',
        },
    },

    'loggers': {
        'subscriptions': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },

        # NEW LOGGER → For our debugging middleware
        'request_debugger': {
            'handlers': ['request_debug_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLITE_PATH lets us point the DB at a persistent volume in production
# (e.g. /data/db.sqlite3 on Fly.io). Defaults to the project dir for local dev.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': config('SQLITE_PATH', default=str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "static",  # adjust this based on where your CSS files are
]

# WhiteNoise: compressed, cache-busted static file serving in production.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Media files settings. MEDIA_ROOT can point at a persistent volume in production.
MEDIA_URL = '/media/'
MEDIA_ROOT = config('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'EXCEPTION_HANDLER': 'frontend.exceptions.custom_exception_handler',
}

# mail settings (Resend SMTP)
# Port 587 (STARTTLS) is blocked on some networks/ISPs; 465 (implicit SSL) is the
# reliable default. Override EMAIL_PORT / EMAIL_USE_SSL in .env per environment.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_HOST_USER = 'resend'
EMAIL_HOST_PASSWORD = config('RESEND_API_KEY', default='')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='One Million Jobs <onboarding@resend.dev>')

# Use the console backend locally (prints emails to the terminal) by setting
# EMAIL_USE_CONSOLE=True in .env, so dev work doesn't burn Resend quota.
if config('EMAIL_USE_CONSOLE', default=False, cast=bool):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# -----USE LOCALLY-------

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'iyiolaolubusola@gmail.com'
# EMAIL_HOST_PASSWORD = config('GMAIL_APP_PASSWORD', default='')
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# -----USE ON THE SERVER------

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'freelancetesting.onemillionjobs.com.ng'  # cPanel mail server
# EMAIL_PORT = 465                                       # SMTP SSL port
# EMAIL_USE_SSL = True                                   # use SSL
# EMAIL_USE_TLS = False                                  # disable TLS
# EMAIL_HOST_USER = 'noreply@freelancetesting.onemillionjobs.com.ng'
# EMAIL_HOST_PASSWORD = config('CPANEL_EMAIL_PASSWORD', default='')
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# social login settings
GOOGLE_OAUTH2_CLIENT_ID = config('GOOGLE_OAUTH2_CLIENT_ID', default='')
GOOGLE_OAUTH2_CLIENT_SECRET = config('GOOGLE_OAUTH2_CLIENT_SECRET', default='')

# Google Maps JavaScript API key (used by the maps/autocomplete widgets)
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='')
GOOGLE_OAUTH2_REDIRECT_URI = "http://127.0.0.1:8000/api/auth/google/callback/" # for local testing
# GOOGLE_OAUTH2_REDIRECT_URI = "http://freelancetesting.onemillionjobs.com.ng/api/auth/google/callback/" # for production
# GOOGLE_OAUTH2_REDIRECT_URI = "https://lichtcode.pythonanywhere.com/api/auth/google/callback/" # for pythonanywhere


# JWT settings
# These settings are for the Simple JWT package, which provides JSON Web Token authentication.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_COOKIE': 'access',  # Optional, if you want to store access token in a cookie too
}

COOKIE_KWARGS = dict(
    httponly=True,
    secure=not DEBUG,    
)

VAT_ENABLED = True  # Set to True if you want to apply VAT
VAT_RATE = 20  # VAT rate in percentage, e.g., 20 for 20%. Used by subscription checkout.

PLATFORM_FEE_PERCENTAGE = 10

# Job/escrow payments: the platform commission (PLATFORM_FEE_PERCENTAGE) is taken
# from the freelancer at release, and VAT is charged ON THAT COMMISSION (the
# platform's service fee) -- not on the freelancer's earnings or the escrow
# amount. This mirrors Upwork/Fiverr/Freelancer.com. Kept separate from the
# subscription VAT_RATE so the two can differ (Nigeria VAT is 7.5%).
ESCROW_VAT_ENABLED = True
ESCROW_VAT_RATE = 7.5  # percentage applied to the commission, e.g. 7.5 for 7.5%

# Freelancer Pro perk: new jobs are visible only to Pro freelancers (and
# employers/admins) for this many hours before everyone else sees them.
EARLY_ACCESS_HOURS = 12  # Platform fee as a percentage of the transaction amount

# User: onemilm5_freelance_online

# Database: onemilm5_freelance
