# Generated by Django 5.2.3 on 2025-12-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=250)),
                ("brand_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("accounting_and_finance", "Accounting and Finance"),
                            ("clerical_and_data_entry", "Clerical and Data Entry"),
                            ("customer_service", "Customer Service"),
                            ("engineering_and_technical", "Engineering and Technical"),
                            ("healthcare", "Healthcare"),
                            ("hospitality_and_tourism", "Hospitality and Tourism"),
                            ("information_technology", "Information Technology"),
                            ("legal", "Legal"),
                            ("marketing_and_advertising", "Marketing and Advertising"),
                            (
                                "sales_and_business_development",
                                "Sales and Business Development",
                            ),
                            (
                                "skilled_trades_and_services",
                                "Skilled Trades and Services",
                            ),
                            ("education_and_training", "Education and Training"),
                            ("creative_and_design", "Creative and Design"),
                            (
                                "real_estate_and_property_management",
                                "Real Estate and Property Management",
                            ),
                            (
                                "transportation_and_logistics",
                                "Transportation and Logistics",
                            ),
                            (
                                "construction_and_maintenance",
                                "Construction and Maintenance",
                            ),
                            ("research_and_development", "Research and Development"),
                            (
                                "non_profit_and_volunteering",
                                "Non-Profit and Volunteering",
                            ),
                            (
                                "government_and_public_service",
                                "Government and Public Service",
                            ),
                            ("media_and_entertainment", "Media and Entertainment"),
                            ("telecommunications", "Telecommunications"),
                            ("energy_and_utilities", "Energy and Utilities"),
                            (
                                "agriculture_and_environment",
                                "Agriculture and Environment",
                            ),
                            ("science_and_technology", "Science and Technology"),
                        ],
                        max_length=250,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("tin", models.CharField(blank=True, max_length=250, null=True)),
                ("established_date", models.DateTimeField(blank=True, null=True)),
                (
                    "company_size",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "headquarters_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("primary_phone", models.CharField(blank=True, max_length=50)),
                ("secondary_phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=250, unique=True)),
                ("website", models.CharField(blank=True, max_length=250, unique=True)),
                ("facebook", models.CharField(blank=True, max_length=250, unique=True)),
                ("linkedin", models.CharField(blank=True, max_length=250, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company_logo/"),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="company_documents/"
                    ),
                ),
                (
                    "company_country",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
