# Generated by Django 5.2.3 on 2026-07-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_email_alter_company_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
